server:
  port: 8010
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: MyMTGLibrary
  resources:
    add-mappings: true

mongo:
  mongoUri: mongodb://localhost:27017/
  databaseName: MyMTGLibrary
  collectionName: Cards